service: frontend
runtime: nodejs18  # Gunakan nodejs18 sebagai runtime yang didukung

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /_next/static
  static_dir: .next/static

- url: /.*
  script: auto
